### ISSUE TITLE
SkillAPI Hologram not showing the correct EXP

### ISSUE THREAD

**Issue by Zatvello** [JustDJplease/ExperienceBooster#1]
I Spawned MythicMobs Mob, killed it and did not show the correct exp. Look:

![2018-03-17_00 18 35](https://user-images.githubusercontent.com/37464317/37551231-b1ce060a-297a-11e8-9c59-f091d358ab81.png)

**Comment by demonslayer147** [comment]
I got the same issue as you, I already make a thread on the spigot forum already.

http://prntscr.com/ismgl8

**Comment by JustDJplease** [comment]
This issue has to do with custom skillapi experience from mythicmobs. I am currently not checking this mythicmobs feature. This should be fixed in an upcoming update.

**Comment by JustDJplease** [comment]
May or may not be fixed with the upcoming 1.16 update. May drop support for SkillAPI.
